---
title: "Assignment Example"
output: html_document
bibliography: "refs.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The Relationship of Emotion to Cognition: A Functional Approach to a Semantic Controversy. (1987) Leventhal, H. & Scherer, K. 

@leventhal1987relationship suggests that the on-going debate between whether or not emotion can precede cognition (and is therefore independent of it) (referring to Zajonc, 1980), or whether that it is "secondary and largely dependent on cognition" (based on @lazarus1966psychological, 1982) (p. 3) is to get lost in a nearly pointless labyrinth of definition making. That is to say: can emotion be defined as a purely automatic response that doesn't require cognition, e.g. an "escape reaction" (@zajonc1980feeling qtd. p. 5)? Or is something like an escape reaction not an emotion and merely a stimulus, and it takes cognition to "analyze" the stimulus and then emotion (or in this case escape reaction) is activated/ felt ? It depends again on how one defines stimulus, emotion and cognition. The paper wants to move beyond this debate by preventing a model that at certain levels of "experience" favor one or the other possibilities. For instance, at the sensory-motor level it appears emotion may be felt sans cognition, but beyond that it seems that a schematic and conceptual level are engaged. As an example, Zajonc says a frog has "encoding" that suggests any change in the environment that has been "encoded" as dangerous is sent, so to speak, via the retina "by a direct  pathway to hypothalamic response centres" (p. 6). Lazarus aggress, but thinks that the encoding is not entirely automatic and requires some processing, which he considers cognition. We fall again into the definitional problem. @leventhal1987relationship says that emotion is a multicomponent process - and that is the proper way to look at the relationship between cognition and emotion. Instead of asking what is emotion or cognition we ask what about the process? They suggest one type of emotional reaction, beyond sensory motor, is schematic, which is automatic and built from memories.(In children, for instance, the autonomic nervous system builds up these memories). Perception to similar memories triggers an emotion (which "both Lazarus and Zajonc would call cognition (memory of situational stimuli) (p. 10)  The final level of the process is conceptual, which is the thinking about feelings in a specific "temporal framework" as well as other frameworks like the sense of self and "key people in the social environment" (p. 11). They suggest that "while we may characterize a stimulus, e.g. a live snake, as 'emotional' because it is a relative activator of autonomic or expressive behavior, its activation of the cognitive or perceptual components of the schema is likely to be so nearly simultaneous with the activation of the expressive and autonomic component, as to NEGATE the significance of Zajonc's suggestion that emotional mechanism operate prior to and independent to cognitive mechanisms" (p. 12-3). In summation, "the arousal of a schema, whether by an external or internal stimulus or a shift in level of a hormone or neurotransmitter, implies the SIMULTANEOUS activation of cognitive (situation) and emotion 9expressive, subjective feeling) components. What may take more or less time, or what may be more or less salient, is the ability of the observer to identify, label, and report upon the 'emotional' and 'cognitive' attributes of consciousness" p. 24.) 

# An Appraisal-Driven Componential Approach to the Emotional Brain. (2018) Sander D.; Gradjean, D.; and Scherer, K.R. 

@sander2018appraisal notes that certain areas of the brain "are particualrly related to individual emotions" and other parts of the brain are repsonsible for "families of emotions" (p. 219). The paper, like @leventhal1987relationship is attemping to combine two different approaches. It has some simliarites to @leventhal1987relationship's paper that suggests component similar worrking in parallel (or at least so quickly togeter they might as well be simultaneous.) Also like @leventhal1987relationship who belive that many of the competing "contradicotry" theories are actually "compliementary." They suggest "five fucniatally defined neural networks" (p. 219) that give rise to emotion. They also develop a process that produces emotion and it may be useful to comapre that to @leventhal1987relationship's three process model of stimulus-response emotion, schematic emotion, and finally, conceptual emotion. @sander2018appraisal prpose that there is an "appraising brain" - a sort of always "looking" brain that monitors the environment (internally and extenrally) and is extraconscious.  When it detects some internal or external event it activates an "elicitation network", an "expression network" an "action tendency network", an "feeling network" and an "autonomic reaction newtork" (p. 227). This is all syncoroniszed and at the activation of the "feeling network" this gives rise to "conscious experience." These networks are "interrelated" and again appear to happen all at once, or like @leventhal1987relationship suggests they might as well be simulatneous. 

# References


